export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  HR_MANAGER = 'HR_MANAGER',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum EmploymentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  TERMINATED = 'TERMINATED',
  PROBATION = 'PROBATION',
}

export enum ContractType {
  INDEFINITE = 'INDEFINITE',
  FIXED_TERM = 'FIXED_TERM',
  PART_TIME = 'PART_TIME',
  INTERNSHIP = 'INTERNSHIP',
  FREELANCE = 'FREELANCE',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ChatMode {
  EMPLOYEE = 'EMPLOYEE',
  MANAGER = 'MANAGER',
  CONFIDENTIAL = 'CONFIDENTIAL',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  REMOTE = 'REMOTE',
  HOLIDAY = 'HOLIDAY',
  VACATION = 'VACATION',
  SICK_LEAVE = 'SICK_LEAVE',
}

export enum PerformanceRating {
  OUTSTANDING = 'OUTSTANDING',
  EXCEEDS = 'EXCEEDS',
  MEETS = 'MEETS',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  UNSATISFACTORY = 'UNSATISFACTORY',
}

export enum PlanTier {
  STARTER = 'STARTER',
  BUSINESS = 'BUSINESS',
  ENTERPRISE = 'ENTERPRISE',
}

export enum IntegrationStatus {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
  PENDING = 'PENDING',
}

export enum AutomationTrigger {
  EMPLOYEE_HIRED = 'EMPLOYEE_HIRED',
  EMPLOYEE_TERMINATED = 'EMPLOYEE_TERMINATED',
  BIRTHDAY = 'BIRTHDAY',
  ANNIVERSARY = 'ANNIVERSARY',
  ABSENCE_THRESHOLD = 'ABSENCE_THRESHOLD',
  RISK_SCORE_CHANGE = 'RISK_SCORE_CHANGE',
  CONTRACT_EXPIRY = 'CONTRACT_EXPIRY',
  PERFORMANCE_REVIEW_DUE = 'PERFORMANCE_REVIEW_DUE',
  PAYROLL_CLOSED = 'PAYROLL_CLOSED',
  SCHEDULE = 'SCHEDULE',
}
